[package]
name = "skews-ui"
description = "Elements, styles, animation and scene construction."
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
authors.workspace = true
repository.workspace = true

[lints]
workspace = true

[dependencies]
skews-core = { workspace = true }
