[package]
name = "skews-shell"
description = "The rusty-skews shell binary."
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
authors.workspace = true
repository.workspace = true
publish.workspace = true

[[bin]]
name = "rusty-skews"
path = "src/main.rs"

[lints]
workspace = true

[dependencies]
anyhow = { workspace = true }
clap = { workspace = true }
tracing = { workspace = true }
tracing-subscriber = { workspace = true }
skews-core = { workspace = true }
skews-config = { workspace = true }
skews-theme = { workspace = true }
skews-render = { workspace = true }
skews-wayland = { workspace = true }
wgpu = { workspace = true }
skews-app = { workspace = true }
skews-modules = { workspace = true }
skews-layout = { workspace = true }
skews-text = { workspace = true }
skews-ui = { workspace = true }
calloop = { workspace = true }
calloop-wayland-source = { workspace = true }
notify = { workspace = true }
skews-ipc-hyprland = { workspace = true }
