[package]
name = "skews-text"
description = "Text shaping, font fallback and glyph atlas."
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
authors.workspace = true
repository.workspace = true
publish.workspace = true

[lints]
workspace = true

[dependencies]
cosmic-text = { workspace = true }
thiserror = { workspace = true }
